services:
  - type: web
    name: translator-api
    env: python
    plan: free
    rootDir: GENAI
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn translator:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000

